AeqPlotDarkMode=true
AudioAppBlocklist=
AudioAppBlocklistInvert=false
AudioOutputDevice=alsa_output.usb-Generic_USB_Audio-00.HiFi__Headphones__sink
AudioOutputUseDefault=true
AudioVirtualSinkForceMaxValue=false
AutoStartEnabled=true
BenchmarkCacheC0=3.16007e-07;5.82655e-07;1.34467e-06;3.14551e-06;6.92612e-06;1.62406e-05;4.24098e-05;0.000106327;0.000297957;0.000799605
BenchmarkCacheC1=7.6228e-08;1.54085e-07;3.05978e-07;6.0903e-07;1.21691e-06;2.44852e-06;4.94926e-06;9.83415e-06;1.94568e-05;4.12768e-05
EqualizerShowHandles=true
ExecutablePath=/usr/bin/jamesdsp
LastWindowGeometry=AdnQywADAAAAAAABAAAAGQAABPQAAAV9AAAAAQAAABkAAAT0AAAFfQAAAAACAAAACgAAAAABAAAAGQAABPQAAAV9
SetupDone=true
Theme=qt6ct-style
ThemeColors=default
TrayIconMenu=passthrough;menu_preset;separator;reload;show;quit;
VdcLastDatabaseId=3666759067
