AeqPlotDarkMode=true
AudioAppBlocklist=
AudioAppBlocklistInvert=false
AudioOutputDevice=alsa_output.usb-Generic_USB_Audio-00.HiFi__Headphones__sink
AudioOutputUseDefault=true
AudioVirtualSinkForceMaxValue=false
AutoStartEnabled=true
BenchmarkCacheC0=3.12975e-07;5.61554e-07;1.34923e-06;3.03862e-06;6.77119e-06;1.59908e-05;4.19105e-05;0.00010638;0.00030129;0.000839843
BenchmarkCacheC1=7.35781e-08;1.54758e-07;3.01186e-07;6.08126e-07;1.20172e-06;2.41082e-06;4.96654e-06;9.91675e-06;1.92432e-05;3.57817e-05
EqualizerShowHandles=true
ExecutablePath=/usr/bin/jamesdsp
LastWindowGeometry=AdnQywADAAAAAAABAAAAGQAABPUAAAV/AAAAAQAAABkAAAT1AAAFfwAAAAACAAAACgAAAAABAAAAGQAABPUAAAV/
SetupDone=true
Theme=qt6ct-style
ThemeColors=default
TrayIconMenu=passthrough;menu_preset;separator;reload;show;quit;
VdcLastDatabaseId=3666759067
