AeqPlotDarkMode=true
AudioAppBlocklist=
AudioAppBlocklistInvert=false
AudioOutputDevice=alsa_output.usb-Generic_USB_Audio-00.HiFi__Headphones__sink
AudioOutputUseDefault=true
AudioVirtualSinkForceMaxValue=false
AutoStartEnabled=true
BenchmarkCacheC0=3.00546e-07;5.70082e-07;1.32659e-06;3.48007e-06;7.41163e-06;1.5889e-05;4.21748e-05;0.000108793;0.000305173;0.00083783
BenchmarkCacheC1=7.4846e-08;1.54061e-07;3.14723e-07;5.64017e-07;1.19516e-06;2.44708e-06;4.98131e-06;9.74345e-06;1.88563e-05;3.99202e-05
EqualizerShowHandles=true
ExecutablePath=/usr/bin/jamesdsp
LastWindowGeometry=AdnQywADAAAAAAABAAAAGQAABPUAAAV6AAAAAQAAABkAAAT1AAAFegAAAAACAAAACgAAAAABAAAAGQAABPUAAAV6
SetupDone=true
Theme=qt6ct-style
ThemeColors=default
TrayIconMenu=passthrough;menu_preset;separator;reload;show;quit;
VdcLastDatabaseId=3666759067
