# hyprlang noerror false
# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5

# User apps
exec-once = bash -c "sleep 3 && vesktop"
exec-once = jamesdsp --tray
exec-once = valent --gapplication-service
exec-once = bash -c "sleep 5 && ~/.config/hypr/custom/scripts/generate-wallpaper-thumbs.sh"

# Refresh Quickshell components on startup
exec-once = ~/.config/hypr/custom/scripts/refresh-quickshell.sh

# Persistent lock screen launcher
exec-once = sleep 0.5 && ~/.config/qylock/smart_lock.sh

# Surge download manager daemon
exec-once = surge server start
