-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Ghost")
hl.env("XCURSOR_SIZE", "36")

-- Settings
hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 5,
    },
})
