# Don't print a new line at the start of the prompt
add_newline = false
# Pipes ╰─ ╭─
# Powerline symbols                                     
# Wedges 🭧🭒 🭣🭧🭓
# Random noise 🬖🬥🬔🬗
# Cool stuff 󰜥   

format = """
$cmd_duration 󰜥 $directory $git_branch
$character"""

# Replace the "❯" symbol in the prompt with "➜"
[character]                            
success_symbol = "[   ](bold fg:#b8c4ff)"
error_symbol = "[   ](bold fg:#ffb4ab)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
style = "bg:#e4bad9"
symbol = "󰘬"
truncation_length = 12
truncation_symbol = ""
format = "󰜥 [](bold fg:#e4bad9)[$symbol $branch(:$remote_branch)](fg:#121318 bg:#e4bad9)[ ](bold fg:#e4bad9)"

[git_commit]
commit_hash_length = 4
tag_symbol = " "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
conflicted = " 🏳 "
ahead = " 🏎💨 "
behind = " 😰 "
diverged = " 😵 "
untracked = " 🤷 ‍"
stashed = " 📦 "
modified = " 📝 "
staged = '[++\($count\)](green)'
renamed = " ✍️ "
deleted = " 🗑 "

[hostname]
ssh_only = false
format =  "[•$hostname](bg:#e4bad9 bold fg:#121318)[](bold fg:#e4bad9)"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed green"

[time]
disabled = true
format = '🕙[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "bold bg:#e4bad9 fg:#121318"
style_root = "red bold"
format = "[](bold fg:#e4bad9)[$user]($style)"
disabled = false
show_always = true

[directory]
home_symbol = "  "
read_only = "  "
style = "bg:#b8c4ff fg:#121318"
truncation_length = 6
truncation_symbol = " ••/"
format = '[](bold fg:#b8c4ff)[󰉋 $path]($style)[](bold fg:#b8c4ff)'

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"GitHub" = " 󰊤 "

[cmd_duration]
min_time = 0
format = '[](bold fg:#c2c5dd)[󰪢 $duration](bold bg:#c2c5dd fg:#121318)[](bold fg:#c2c5dd)'
