-- MANAGED BY HYPRSET.LUA — DO NOT EDIT
hl.config({general={layout="scrolling"}})
hl.config({ decoration = { active_opacity = 1 } })
hl.config({ general = { border_size = 2 } })
hl.config({ decoration = { blur = { enabled = true } } })
hl.config({ general = { gaps_in = 2 } })
hl.config({ decoration = { blur = { passes = 6 } } })
hl.config({ animations = { enabled = true } })
hl.config({ input = { repeat_delay = 250 } })
hl.config({ general = { gaps_out = 5 } })
hl.config({ input = { repeat_rate = 35 } })
hl.config({ decoration = { rounding = 3 } })
hl.config({ decoration = { blur = { size = 5 } } })
hl.config({ general = { layout = "scrolling" } })
hl.config({ input = { touchpad = { scroll_factor = 0.1 } } })
hl.config({ input = { numlock_by_default = true } })
hl.config({ input = { touchpad = { natural_scroll = false } } })
hl.config({ input = { kb_layout = "us" } })
hl.config({ input = { touchpad = { clickfinger_behavior = false } } })
hl.config({ decoration = { inactive_opacity = 0.99 } })
hl.config({ input = { touchpad = { disable_while_typing = false } } })
hl.config({ input = { follow_mouse = 1 } })
