-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Original-Classic")
hl.env("XCURSOR_SIZE", "36")

-- Settings
hl.config({
    decoration = {
        rounding = 4,
        shadow = {
            enabled = true,
        },
    },
    general = {
        border_size = 1,
        extend_border_grab_area = 8,
        gaps_in = 4,
        gaps_out = 5,
    },
})

-- Bezier curves
hl.curve("menu_decel", { type = "bezier", points = { {0.1, 1.0}, {0.0, 1.0} } })

-- Animations
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 7.0,
    bezier = "menu_decel",
    style = "slide",
})
