-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Ghost")
hl.env("XCURSOR_SIZE", "36")

-- Settings
hl.config({
    decoration = {
        rounding = 6,
        blur = {
            enabled = true,
            size = 10,
        },
        shadow = {
            enabled = true,
        },
        dim_inactive = true,
    },
    general = {
        extend_border_grab_area = 8,
        border_size = 1,
        gaps_in = 4,
        gaps_out = 5,
        layout = "dwindle",
    },
})

-- Bezier curves
hl.curve("custom1", { type = "bezier", points = { {0.0, 1.099}, {0.995, 0.503} } })

-- Animations
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 5.0,
    bezier = "custom1",
})
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 8.0,
    bezier = "custom1",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 8.0,
    bezier = "custom1",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 4.0,
    bezier = "custom1",
    style = "slide",
})
