general {
    # col.active_border = rgba(978e9877)
    # col.inactive_border = rgba(4b444d55)

    # Option 1: Solid Primary (Standard Material You Accent)
    col.active_border = rgba(e1b8f5ff)

    # Option 2: Vibrant Gradient (Primary to Tertiary)
    # col.active_border = rgba(e1b8f5ff) rgba(f4b7b8ff) 45deg

    # Option 3: Subtle Gradient (Primary to Primary Container)
    # col.active_border = rgba(e1b8f5ff) rgba(5a396dff) 45deg

    # Option 4: High Contrast (Inverse Primary)
    # col.active_border = rgba(735187ff)

    col.inactive_border = rgba(978e9855)
}

misc {
    background_color = rgba(161217FF)
}

plugin {
    hyprbars {
        # Honestly idk if it works like css, but well, why not
        bar_text_font = Google Sans Flex Medium, Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgba(161217FF)
        col.text = rgba(e9e0e7FF)


        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(e9e0e7), 13, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(e9e0e7), 13, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(e9e0e7), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
    }
}

windowrule = border_color rgba(e1b8f5AA) rgba(e1b8f577), match:pin 1
